# Kustomization 配置文件
# 用于组织和管理重调度器的所有部署资源

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rescheduler-scheduler
  annotations:
    config.kubernetes.io/local-config: "true"

# 资源文件列表
resources:
  - rbac.yaml           # RBAC权限配置
  - config.yaml         # 调度器配置
  - scheduler.yaml      # 调度器部署

# 命名空间
namespace: kube-system

# 通用标签
commonLabels:
  app: rescheduler-scheduler
  managed-by: kustomize
  version: v1.0.0

# 通用注解
commonAnnotations:
  config.kubernetes.io/origin: |
    path: manifests/rescheduler/kustomization.yaml
  docs.kubernetes.io/description: "Kubernetes重调度器插件部署配置"

# 镜像配置
images:
  - name: scheduler-plugins
    newTag: latest

# 配置生成器
configMapGenerator:
  - name: rescheduler-deployment-info
    literals:
      - deployment.version=v1.0.0
      - deployment.date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - deployment.description=Kubernetes重调度器智能调度系统

# 变量替换
replacements:
  - source:
      kind: ConfigMap
      name: rescheduler-deployment-info
      fieldPath: data.deployment\.version
    targets:
      - select:
          kind: Deployment
          name: rescheduler-scheduler
        fieldPaths:
          - metadata.labels.version
          - spec.template.metadata.labels.version

# 修补配置（用于不同环境的定制）
patchesStrategicMerge:
  # 根据需要可以在这里添加环境特定的修补文件
  # - patches/production.yaml
  # - patches/development.yaml

# JSON 修补
patchesJson6902: []

# 生成选项
generatorOptions:
  disableNameSuffixHash: true
  labels:
    managed-by: kustomize
  annotations:
    config.kubernetes.io/origin: "kustomization"
