apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-4
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-5
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-6
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-7
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-8
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-9
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-10
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always

