apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler  # 使用我们的自定义调度器
  containers:
  - name: test-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler
  containers:
  - name: test-container
    image: busybox:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m"
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  namespace: default
  labels:
    app: hello-test
spec:
  schedulerName: hello-scheduler
  containers:
  - name: test-container
    image: alpine:latest
    command: ["sh", "-c", "while true; do echo Hello World; sleep 30; done"]
    resources:
      requests:
        memory: "16Mi"
        cpu: "50m"
      limits:
        memory: "32Mi"
        cpu: "100m"
  restartPolicy: Always
